services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - "8000:8000"
    networks:
      - redis-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
      - redis
    ports:
      - "5173:5173"

  redis:
    image: redis:latest
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge